#!/usr/bin/env python3
"""检查交易逻辑问题的诊断脚本"""

# 问题分析

print("=" * 80)
print("交易逻辑问题诊断")
print("=" * 80)

print("\n【问题1】开仓价格问题")
print("-" * 80)
print("发现：pending_orders中存储的是 entry_price = 75（美分单位）")
print("但是在 settle_position 中会转换为 0-1 格式")
print("结论：价格格式正确，不是问题")

print("\n【问题2】同时持有YES和NO的可能性")
print("-" * 80)
print("可能原因：")
print()
print("原因1: 两个订单同时成交")
print("  - YES和NO在同一时刻成交")
print("  - wait_for_execution检测到其中一个成交")
print("  - 调用_cancel_pending_orders()取消另一个")
print("  - 但是另一个已经成交，取消失败")
print("  - 结果：current_position只记录了一个，但实际持有两个")
print()
print("原因2: 周期结束后订单仍挂着")
print("  - wait_for_execution超时后不再监控")
print("  - 订单继续挂着")
print("  - 后来价格变动，两个订单都成交了")
print("  - 结果：持有YES和NO，但没有current_position记录")
print()
print("原因3: pending_orders未正确清空")
print("  - 某个bug导致pending_orders没有正确清空")
print("  - 下一个周期时又添加了新订单")
print("  - 结果：pending_orders中同时有多个周期的订单")

print("\n【问题3】开仓价位不对")
print("-" * 80)
print("检查点：")
print("1. place_dual_orders中下单价格：entry_price（配置值）")
print("2. pending_orders中存储的价格：entry_price（配置值）")
print("3. current_position中存储的价格：order_info['price']（从pending_orders获取）")
print()
print("可能原因：")
print("- 如果最小股数被调整，订单金额会改变")
print("- 但是价格还是配置的开仓价，不会改变")
print("- 所以开仓价位应该是正确的")

print("\n【关键检查点】")
print("-" * 80)
print("1. pending_orders是否在每次周期开始时清空？")
print("2. current_position是否在每次周期结束时清空？")
print("3. 订单取消逻辑是否正确？")
print()

# 检查代码逻辑
print("\n【代码逻辑检查】")
print("-" * 80)

print("\n1. pending_orders 清空时机：")
print("   - _cancel_pending_orders() 会清空")
print("   - 在订单成交后调用（第1004行）")
print("   - 在周期结束未成交时调用（第490行）")
print("   ✓ 逻辑正确")

print("\n2. current_position 清空时机：")
print("   - close_position() 中清空（第1481行）")
print("   - 在平仓时调用")
print("   ✓ 逻辑正确")

print("\n3. 可能的BUG：")
print("   ⚠️  第1020-1027行：wait_for_execution 超时后不取消订单")
print("   ⚠️  这可能导致订单继续挂着，后来成交了")
print("   ⚠️  建议：周期结束时应该取消所有未成交订单")

print("\n【建议修复】")
print("-" * 80)
print("1. 在周期结束时，确保取消所有pending_orders")
print("2. 在execute_trade_cycle开始时，清空pending_orders")
print("3. 添加日志记录订单创建和成交的详细信息")
print("4. 在成交检测时，检查两个订单是否都成交了")
print()
